// Conținutul cursului Arhitectura Afacerii · Start.
//
// Structura urmează documentul de metodologie (Draft v1, iunie 2026): 10 module,
// 43 de lecții, 10–12 săptămâni. Lecțiile sunt deocamdată titluri fără video —
// `isTrackableLesson` le ignoră, deci nu strică procentele până apare filmarea.
//
// REGULA ID-URILOR: tot ce e aici începe cu 'st-'. Vezi src/lib/courses.ts.
import { Module, LiveEvent } from '../types';

export const START_MODULES: Module[] = [
  {
    id: 'st-m-0',
    title: 'Ce Construiești de Fapt',
    subtitle: 'Claritate înainte de orice construcție.',
    description: 'Înainte să vorbim despre nișă, validare sau vânzări, trebuie să existe claritate despre ce construim și de ce ordinea pașilor contează mai mult decât energia cu care pornești.',
    order_index: 0,
    unlockWeek: 0,
    etapa: 'Etapa 0',
    saptamana: 'Săptămâna 0',
    deliverable: 'Înțelegi diferența reală dintre tipurile de structuri de business și decizi conștient ce construiești — nu din entuziasm, ci din claritate.',
    lessons: [
      {
        id: 'st-l-0-1',
        module_id: 'st-m-0',
        title: 'Business vs. Freelancing vs. Job cu Firmă Proprie',
        description: 'Cele trei forme de activitate independentă și de ce diferența nu e juridică, ci structurală. Un freelancer vinde timp. Un antreprenor construiește un sistem.',
        video_url: '',
        duration_min: 0,
        order_index: 1,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-0-2',
        module_id: 'st-m-0',
        title: 'De Ce Eșuează 80% din Afacerile Noi',
        description: 'Cei 3 factori comuni ai eșecului din consultațiile reale: pornesc fără validare, construiesc fără sistem, vând fără strategie.',
        video_url: '',
        duration_min: 0,
        order_index: 2,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-0-3',
        module_id: 'st-m-0',
        title: 'Erorile de Mentalitate Care Omoară Afacerile Înainte să Înceapă',
        description: 'Pasiunea ca criteriu de nișă, energia ca substitut al sistemului, capcana pregătirii infinite. Construiești pentru supraviețuire sau pentru scalare?',
        video_url: '',
        duration_min: 0,
        order_index: 3,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-0-ex-1',
        module_id: 'st-m-0',
        title: 'Livrabilul modulului · Ce Construiești de Fapt',
        description: 'Înțelegi diferența reală dintre tipurile de structuri de business și decizi conștient ce construiești — nu din entuziasm, ci din claritate.',
        video_url: '',
        duration_min: 0,
        order_index: 4,
        is_published: true,
        type: 'exercise',
        exercise_id: 'st-e-0-1',
      },
    ],
    exercises: [
      {
        id: 'st-e-0-1',
        module_id: 'st-m-0',
        title: 'Livrabilul modulului · Ce Construiești de Fapt',
        description: 'Înțelegi diferența reală dintre tipurile de structuri de business și decizi conștient ce construiești — nu din entuziasm, ci din claritate.',
        order_index: 1,
      },
    ],
  },
  {
    id: 'st-m-1',
    title: 'Nișa și Ideea',
    subtitle: 'Nișa se alege cu metodă, nu cu intuiție.',
    description: 'Cel mai frecvent răspuns greșit la „ce business fac" e fie prea larg, fie prea pasional. Nișa se alege cu metodă, nu cu intuiție și nu cu pasiune.',
    order_index: 1,
    unlockWeek: 1,
    etapa: 'Modulul 1',
    saptamana: 'Săptămâna 1',
    deliverable: 'Ai o nișă aleasă cu metodă și știi dacă piața există — nu prin prezumție, ci prin dovezi de suprafață.',
    lessons: [
      {
        id: 'st-l-1-1',
        module_id: 'st-m-1',
        title: 'Cererea, Nu Pasiunea',
        description: 'Diferența fundamentală între o pasiune și o piață. Oamenii cumpără soluții la probleme, nu produse ale pasiunii tale.',
        video_url: '',
        duration_min: 0,
        order_index: 1,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-1-2',
        module_id: 'st-m-1',
        title: 'Matricea Nișei: Cerere × Competiție × Capacitate',
        description: 'Cele 3 axe pe care evaluezi orice nișă. Absența competiției nu e un semn bun — e un semn de îngrijorare.',
        video_url: '',
        duration_min: 0,
        order_index: 2,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-1-3',
        module_id: 'st-m-1',
        title: 'Testul Rapid de Nișă: 72 de Ore',
        description: 'Ce poți verifica fără să investești nimic: concurenți activi, grupuri online, recenzii negative, anunțuri de angajare.',
        video_url: '',
        duration_min: 0,
        order_index: 3,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-1-4',
        module_id: 'st-m-1',
        title: 'Poziționarea Inițială',
        description: 'Nu trebuie să fii inovator. Trebuie să fii mai bun sau mai specific pentru un segment. Diferențierea prin specificitate.',
        video_url: '',
        duration_min: 0,
        order_index: 4,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-1-ex-1',
        module_id: 'st-m-1',
        title: 'Livrabilul modulului · Nișa și Ideea',
        description: 'Ai o nișă aleasă cu metodă și știi dacă piața există — nu prin prezumție, ci prin dovezi de suprafață.',
        video_url: '',
        duration_min: 0,
        order_index: 5,
        is_published: true,
        type: 'exercise',
        exercise_id: 'st-e-1-1',
      },
    ],
    exercises: [
      {
        id: 'st-e-1-1',
        module_id: 'st-m-1',
        title: 'Livrabilul modulului · Nișa și Ideea',
        description: 'Ai o nișă aleasă cu metodă și știi dacă piața există — nu prin prezumție, ci prin dovezi de suprafață.',
        order_index: 1,
      },
    ],
  },
  {
    id: 'st-m-2',
    title: 'Validarea Ideii',
    subtitle: 'Cel mai important modul din program.',
    description: 'Orice modul ulterior presupune că ai trecut prin validare. Dacă sari peste asta, construiești pe nisip. Validarea nu e să afli dacă oamenilor le place ideea — e să afli dacă sunt dispuși să plătească.',
    order_index: 2,
    unlockWeek: 2,
    etapa: 'Modulul 2',
    saptamana: 'Săptămânile 2–3',
    isGate: true,
    deliverable: 'Ai vorbit cu minimum 10 potențiali clienți și ai dovezi clare că ideea are (sau nu are) piață. Nu ai construit nimic încă — sau ai decis conștient să pivotezi.',
    lessons: [
      {
        id: 'st-l-2-1',
        module_id: 'st-m-2',
        title: 'Ce Înseamnă Cu Adevărat „Validat"',
        description: 'Ierarhia dovezilor: complimentul nu valorează nimic, interesul valorează puțin, pre-comanda valorează mult, plata e singura validare reală.',
        video_url: '',
        duration_min: 0,
        order_index: 1,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-2-2',
        module_id: 'st-m-2',
        title: 'MVP-ul Corect',
        description: 'Minimul necesar ca să obții o dovadă de plată. Dacă durează mai mult de 2 săptămâni, e prea complex.',
        video_url: '',
        duration_min: 0,
        order_index: 2,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-2-3',
        module_id: 'st-m-2',
        title: 'Metodele de Validare cu Buget Zero',
        description: 'Cinci metode concrete: conversații directe, pre-vânzarea, postul de testare, landing page cu trafic minimal, propunerea directă.',
        video_url: '',
        duration_min: 0,
        order_index: 3,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-2-4',
        module_id: 'st-m-2',
        title: 'Cum Conduci O Conversație de Validare',
        description: 'Scriptul complet. Greșeala numărul 1: să prezinți ideea și să ceri opinia. Corect: să explorezi problema fără să menționezi soluția.',
        video_url: '',
        duration_min: 0,
        order_index: 4,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-2-5',
        module_id: 'st-m-2',
        title: 'Cum Interpretezi Rezultatele',
        description: 'Semnalele că ideea are piață și cele că nu are. Dacă nu trece, nu e eșec — e informație. Pivotul corect ajustează un element, nu tot.',
        video_url: '',
        duration_min: 0,
        order_index: 5,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-2-ex-1',
        module_id: 'st-m-2',
        title: 'Livrabilul modulului · Validarea Ideii',
        description: 'Ai vorbit cu minimum 10 potențiali clienți și ai dovezi clare că ideea are (sau nu are) piață. Nu ai construit nimic încă — sau ai decis conștient să pivotezi.',
        video_url: '',
        duration_min: 0,
        order_index: 6,
        is_published: true,
        type: 'exercise',
        exercise_id: 'st-e-2-1',
      },
    ],
    exercises: [
      {
        id: 'st-e-2-1',
        module_id: 'st-m-2',
        title: 'Livrabilul modulului · Validarea Ideii',
        description: 'Ai vorbit cu minimum 10 potențiali clienți și ai dovezi clare că ideea are (sau nu are) piață. Nu ai construit nimic încă — sau ai decis conștient să pivotezi.',
        order_index: 1,
      },
    ],
  },
  {
    id: 'st-m-3',
    title: 'Construcția Corectă: Sistematizare',
    subtitle: 'Sistemul e pentru ziua 1, nu pentru când ești mare.',
    description: 'Acum știi că ideea are piață. Înainte să vinzi la scară, construiești sistemul care face livrarea reproductibilă și posibil de delegat. Afacerea fără sistem depinde de tine 24/7 și pe care niciun investitor serios nu o finanțează.',
    order_index: 3,
    unlockWeek: 4,
    etapa: 'Modulul 3',
    saptamana: 'Săptămâna 4',
    deliverable: 'Ai primele 3 documente operaționale ale afacerii scrise. Știi diferența dintre sistematizare și automatizare și de ce ordinea contează.',
    lessons: [
      {
        id: 'st-l-3-1',
        module_id: 'st-m-3',
        title: 'De Ce Construiești Sistemul Înainte să Ai Clienți Mulți',
        description: 'Studiul de caz Victor — Aurelius și Bacio di Bolle. Investitorii nu cumpără ideea ta, cumpără sistemul tău.',
        video_url: '',
        duration_min: 0,
        order_index: 1,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-3-2',
        module_id: 'st-m-3',
        title: 'Cele 3 Documente Esențiale',
        description: 'Fișa produsului, procesul de vânzare, onboardingul clientului. Dacă nu poți scrie fiecare în 1 pagină, nu știi clar ce vinzi.',
        video_url: '',
        duration_min: 0,
        order_index: 2,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-3-3',
        module_id: 'st-m-3',
        title: 'Sistematizare vs. Automatizare',
        description: 'Întâi sistematizezi, abia apoi automatizezi. Nu poți automatiza ce nu ai definit. Dacă automatizezi haosul, ai haos rapid și la scară.',
        video_url: '',
        duration_min: 0,
        order_index: 3,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-3-4',
        module_id: 'st-m-3',
        title: 'Arhitectura Afacerii Tale: Roluri, Responsabilități, Fluxuri',
        description: 'Cele 4 funcții obligatorii ale oricărei afaceri. Ești tu în toate patru — care e planul de ieșire din fiecare?',
        video_url: '',
        duration_min: 0,
        order_index: 4,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-3-5',
        module_id: 'st-m-3',
        title: 'Cum Arată Prima Zi de Operare',
        description: 'Lista operațională, nu cea juridică. Ce să nu faci în prima zi: site, logo, cărți de vizită.',
        video_url: '',
        duration_min: 0,
        order_index: 5,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-3-ex-1',
        module_id: 'st-m-3',
        title: 'Livrabilul modulului · Construcția Corectă: Sistematizare',
        description: 'Ai primele 3 documente operaționale ale afacerii scrise. Știi diferența dintre sistematizare și automatizare și de ce ordinea contează.',
        video_url: '',
        duration_min: 0,
        order_index: 6,
        is_published: true,
        type: 'exercise',
        exercise_id: 'st-e-3-1',
      },
    ],
    exercises: [
      {
        id: 'st-e-3-1',
        module_id: 'st-m-3',
        title: 'Livrabilul modulului · Construcția Corectă: Sistematizare',
        description: 'Ai primele 3 documente operaționale ale afacerii scrise. Știi diferența dintre sistematizare și automatizare și de ce ordinea contează.',
        order_index: 1,
      },
    ],
  },
  {
    id: 'st-m-4',
    title: 'Primele Vânzări',
    subtitle: 'Teoria nu vinde. Conversațiile vând.',
    description: 'Cel mai practic modul din program — fiecare lecție presupune să vorbești cu oameni reali. La final ai făcut vânzări reale sau ești în conversații active.',
    order_index: 4,
    unlockWeek: 5,
    etapa: 'Modulul 4',
    saptamana: 'Săptămâna 5',
    deliverable: 'Ai făcut minimum 1–3 vânzări reale sau ai angajamente ferme în curs. Ai testat scriptul de vânzare și știi ce funcționează.',
    lessons: [
      {
        id: 'st-l-4-1',
        module_id: 'st-m-4',
        title: 'Strategia de Vânzare pentru Prima Lună',
        description: 'Fără ads, fără audiență, fără magie. Ce ai: rețeaua personală, conversații directe, un produs validat. Minimum 3 ore pe zi.',
        video_url: '',
        duration_min: 0,
        order_index: 1,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-4-2',
        module_id: 'st-m-4',
        title: 'Primii 5–10 Clienți: Cine Sunt și Unde Îi Găsești',
        description: 'Nu cel mai profitabil, ci cel mai ușor de convertit și cel mai probabil să dea testimonial și referrals.',
        video_url: '',
        duration_min: 0,
        order_index: 2,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-4-3',
        module_id: 'st-m-4',
        title: 'Scriptul Primei Conversații de Vânzare',
        description: 'Șase etape: conexiunea, diagnosticul, soluția, prețul, obiecțiile, închiderea. Versiune B2C și B2B.',
        video_url: '',
        duration_min: 0,
        order_index: 3,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-4-4',
        module_id: 'st-m-4',
        title: 'Cum Construiești Prețul',
        description: 'Cost plus marjă, prețul pieței, prețul bazat pe valoare. Ieftin nu e un avantaj competitiv sustenabil.',
        video_url: '',
        duration_min: 0,
        order_index: 4,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-4-5',
        module_id: 'st-m-4',
        title: 'Ce Faci după Prima Vânzare',
        description: 'Onboarding activat, feedback real în loc de complimente, testimonial la momentul potrivit, referrals.',
        video_url: '',
        duration_min: 0,
        order_index: 5,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-4-ex-1',
        module_id: 'st-m-4',
        title: 'Livrabilul modulului · Primele Vânzări',
        description: 'Ai făcut minimum 1–3 vânzări reale sau ai angajamente ferme în curs. Ai testat scriptul de vânzare și știi ce funcționează.',
        video_url: '',
        duration_min: 0,
        order_index: 6,
        is_published: true,
        type: 'exercise',
        exercise_id: 'st-e-4-1',
      },
    ],
    exercises: [
      {
        id: 'st-e-4-1',
        module_id: 'st-m-4',
        title: 'Livrabilul modulului · Primele Vânzări',
        description: 'Ai făcut minimum 1–3 vânzări reale sau ai angajamente ferme în curs. Ai testat scriptul de vânzare și știi ce funcționează.',
        order_index: 1,
      },
    ],
  },
  {
    id: 'st-m-5',
    title: 'Marketing și Promovare',
    subtitle: 'Marketingul vine după ce știi că produsul se vinde.',
    description: 'Dacă faci marketing înainte de validare, cheltuiești bani ca să aduci oameni la ceva ce nu știi dacă vor cumpăra. Acum știi că funcționează — acum scalezi.',
    order_index: 5,
    unlockWeek: 6,
    etapa: 'Modulul 5',
    saptamana: 'Săptămânile 6–7',
    deliverable: 'Ai o strategie minimă de marketing pe care o poți executa singur în primele 60 de zile, cu buget mic sau zero.',
    lessons: [
      {
        id: 'st-l-5-1',
        module_id: 'st-m-5',
        title: 'Când Începi Marketingul și Ce Înseamnă Prezență Minimă',
        description: 'Semnalul că ești gata: 2–3 clienți plătitori și știi ce spui care convinge. Prezența nu e marketing.',
        video_url: '',
        duration_min: 0,
        order_index: 1,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-5-2',
        module_id: 'st-m-5',
        title: 'Prima Pagină de Instagram Care Vinde',
        description: 'Diferența între o pagină estetică și una care convertește. Ce conținut vinde la o audiență mică.',
        video_url: '',
        duration_min: 0,
        order_index: 2,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-5-3',
        module_id: 'st-m-5',
        title: 'Primele Campanii Plătite',
        description: 'Nu faci ads dacă postarea organică n-a funcționat deja. Ads amplifică ce există, nu repară ce nu merge.',
        video_url: '',
        duration_min: 0,
        order_index: 3,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-5-4',
        module_id: 'st-m-5',
        title: 'Greșelile de Marketing Care Ard Bugetul',
        description: '„Toată lumea e clientul meu" e o strategie de eșec garantat. Un ad are nevoie de 7–10 zile ca să dea date.',
        video_url: '',
        duration_min: 0,
        order_index: 4,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-5-ex-1',
        module_id: 'st-m-5',
        title: 'Livrabilul modulului · Marketing și Promovare',
        description: 'Ai o strategie minimă de marketing pe care o poți executa singur în primele 60 de zile, cu buget mic sau zero.',
        video_url: '',
        duration_min: 0,
        order_index: 5,
        is_published: true,
        type: 'exercise',
        exercise_id: 'st-e-5-1',
      },
    ],
    exercises: [
      {
        id: 'st-e-5-1',
        module_id: 'st-m-5',
        title: 'Livrabilul modulului · Marketing și Promovare',
        description: 'Ai o strategie minimă de marketing pe care o poți executa singur în primele 60 de zile, cu buget mic sau zero.',
        order_index: 1,
      },
    ],
  },
  {
    id: 'st-m-6',
    title: 'AI în Afacerea Ta',
    subtitle: 'Întâi sistematizezi, apoi automatizezi.',
    description: 'AI e un instrument de lucru pe care concurenții tăi deja îl folosesc. Dar AI fără sistem automatizează haosul. Ordinea e obligatorie.',
    order_index: 6,
    unlockWeek: 8,
    etapa: 'Modulul 6',
    saptamana: 'Săptămâna 8',
    deliverable: 'Ai cel puțin 3 procese din afacerea ta parțial sau complet asistate de AI, cu o economie de timp documentată.',
    lessons: [
      {
        id: 'st-l-6-1',
        module_id: 'st-m-6',
        title: 'Ce Poate Face AI pentru Afacerea Ta Acum',
        description: 'Redactare, cercetare, organizare, suport clienți, generare de idei. Ce nu poate: decizii strategice, relații, judecata ta.',
        video_url: '',
        duration_min: 0,
        order_index: 1,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-6-2',
        module_id: 'st-m-6',
        title: 'Sistematizare vs. Automatizare — Exemple Practice',
        description: 'Dacă nu poți explica procesul unui angajat, nu poți explica AI-ului.',
        video_url: '',
        duration_min: 0,
        order_index: 2,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-6-3',
        module_id: 'st-m-6',
        title: 'Tool-urile AI Esențiale pentru un Starter',
        description: 'Stack minimal cu costuri reale. Ce nu cumperi acum: tool-uri scumpe, agenți complecși, automatizări avansate.',
        video_url: '',
        duration_min: 0,
        order_index: 3,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-6-4',
        module_id: 'st-m-6',
        title: 'Cum Folosești AI ca pe un Angajat, Nu ca pe Google',
        description: 'Promptul bun are context, rol și output așteptat. AI e un junior talentat. Tu ești senior-ul care verifică.',
        video_url: '',
        duration_min: 0,
        order_index: 4,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-6-ex-1',
        module_id: 'st-m-6',
        title: 'Livrabilul modulului · AI în Afacerea Ta',
        description: 'Ai cel puțin 3 procese din afacerea ta parțial sau complet asistate de AI, cu o economie de timp documentată.',
        video_url: '',
        duration_min: 0,
        order_index: 5,
        is_published: true,
        type: 'exercise',
        exercise_id: 'st-e-6-1',
      },
    ],
    exercises: [
      {
        id: 'st-e-6-1',
        module_id: 'st-m-6',
        title: 'Livrabilul modulului · AI în Afacerea Ta',
        description: 'Ai cel puțin 3 procese din afacerea ta parțial sau complet asistate de AI, cu o economie de timp documentată.',
        order_index: 1,
      },
    ],
  },
  {
    id: 'st-m-7',
    title: 'Primul Angajat',
    subtitle: 'Nu angajezi din disperare, nu angajezi din oboseală.',
    description: 'Angajezi când munca poate fi documentată, predată și executată de altcineva la un standard acceptabil — și când costul e acoperit de venituri sau e investiție clară în creștere.',
    order_index: 7,
    unlockWeek: 9,
    etapa: 'Modulul 7',
    saptamana: 'Săptămâna 9',
    deliverable: 'Știi concret dacă e momentul să angajezi și, dacă da, ai profilul de căutare, anunțul și procesul de onboarding pregătite.',
    lessons: [
      {
        id: 'st-l-7-1',
        module_id: 'st-m-7',
        title: 'Când Angajezi: Semnalele Concrete',
        description: 'Ai pierdut clienți din lipsă de capacitate. Ai un task repetitiv de 10+ ore/săptămână. Venitul acoperă costul plus 20% marjă.',
        video_url: '',
        duration_min: 0,
        order_index: 1,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-7-2',
        module_id: 'st-m-7',
        title: 'Ce Angajezi Primul — și Greșelile Comune',
        description: 'Nu angajezi „un om de toate". Nu angajezi un prieten din comoditate. Nu angajezi pe cel mai ieftin.',
        video_url: '',
        duration_min: 0,
        order_index: 2,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-7-3',
        module_id: 'st-m-7',
        title: 'Primul Anunț de Angajare și Selecția',
        description: 'Un anunț bun descurajează oamenii nepotriviți. Include un task mic de testare.',
        video_url: '',
        duration_min: 0,
        order_index: 3,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-7-4',
        module_id: 'st-m-7',
        title: 'Onboarding Rapid: Primele 30 de Zile',
        description: 'Săptămâna 1 înțelege, 2 execută supravegheat, 3 execută independent, 4 evaluare. De aceea ai scris procesele în Modulul 3.',
        video_url: '',
        duration_min: 0,
        order_index: 4,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-7-ex-1',
        module_id: 'st-m-7',
        title: 'Livrabilul modulului · Primul Angajat',
        description: 'Știi concret dacă e momentul să angajezi și, dacă da, ai profilul de căutare, anunțul și procesul de onboarding pregătite.',
        video_url: '',
        duration_min: 0,
        order_index: 5,
        is_published: true,
        type: 'exercise',
        exercise_id: 'st-e-7-1',
      },
    ],
    exercises: [
      {
        id: 'st-e-7-1',
        module_id: 'st-m-7',
        title: 'Livrabilul modulului · Primul Angajat',
        description: 'Știi concret dacă e momentul să angajezi și, dacă da, ai profilul de căutare, anunțul și procesul de onboarding pregătite.',
        order_index: 1,
      },
    ],
  },
  {
    id: 'st-m-8',
    title: 'Structura Financiară de Bază',
    subtitle: 'Afacerile profitabile mor din cash flow.',
    description: 'Structura financiară corectă nu e contabilitate avansată — e claritate de bază pe care orice antreprenor o are din prima zi. Aceleași date curate le cere și orice investitor.',
    order_index: 8,
    unlockWeek: 10,
    etapa: 'Modulul 8',
    saptamana: 'Săptămâna 10',
    deliverable: 'Ai o structură financiară minimă funcțională: banii separați, cash flow monitorizat, pragul de rentabilitate calculat, bugetul construit.',
    lessons: [
      {
        id: 'st-l-8-1',
        module_id: 'st-m-8',
        title: 'Separarea Banilor: Eroarea Numărul 1',
        description: 'Cont de business separat, salariu fix din firmă, cheltuielile personale nu trec prin firmă.',
        video_url: '',
        duration_min: 0,
        order_index: 1,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-8-2',
        module_id: 'st-m-8',
        title: 'Cash Flow: De Ce Omoară Afaceri Profitabile',
        description: 'Poți fi profitabil pe hârtie și fără bani în cont. Monitorizare săptămânală minimă cu un tabel de 4 coloane.',
        video_url: '',
        duration_min: 0,
        order_index: 2,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-8-3',
        module_id: 'st-m-8',
        title: 'Pragul de Rentabilitate și Primul Buget',
        description: 'Costuri fixe / (preț − cost variabil). Tot ce e sub prag e pierdere.',
        video_url: '',
        duration_min: 0,
        order_index: 3,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-8-4',
        module_id: 'st-m-8',
        title: 'Când Reinvestești și Când Scoți Profit',
        description: 'Regula pentru afaceri tinere: 50% rămâne în firmă, 50% e al tău.',
        video_url: '',
        duration_min: 0,
        order_index: 4,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-8-ex-1',
        module_id: 'st-m-8',
        title: 'Livrabilul modulului · Structura Financiară de Bază',
        description: 'Ai o structură financiară minimă funcțională: banii separați, cash flow monitorizat, pragul de rentabilitate calculat, bugetul construit.',
        video_url: '',
        duration_min: 0,
        order_index: 5,
        is_published: true,
        type: 'exercise',
        exercise_id: 'st-e-8-1',
      },
    ],
    exercises: [
      {
        id: 'st-e-8-1',
        module_id: 'st-m-8',
        title: 'Livrabilul modulului · Structura Financiară de Bază',
        description: 'Ai o structură financiară minimă funcțională: banii separați, cash flow monitorizat, pragul de rentabilitate calculat, bugetul construit.',
        order_index: 1,
      },
    ],
  },
  {
    id: 'st-m-9',
    title: 'Cum Funcționează Investițiile',
    subtitle: 'Cunoaștere obligatorie, chiar dacă nu cauți bani mâine.',
    description: 'Dacă nu știi cum funcționează acum, vei lua decizii proaste când momentul vine — sau vei pierde o oportunitate fiindcă nu ești pregătit să o recunoști.',
    order_index: 9,
    unlockWeek: 11,
    etapa: 'Modulul 9',
    saptamana: 'Săptămâna 11',
    deliverable: 'Înțelegi mecanismele de investiție, știi ce face o afacere investabilă, poți calcula o evaluare simplă și identifici ce tip de capital ți se potrivește.',
    lessons: [
      {
        id: 'st-l-9-1',
        module_id: 'st-m-9',
        title: 'Tipurile de Capital',
        description: 'Credit, granturi, equity, parteneriat strategic, acceleratoare, crowdfunding, familie și prieteni — cu contract, nu cu promisiuni.',
        video_url: '',
        duration_min: 0,
        order_index: 1,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-9-2',
        module_id: 'st-m-9',
        title: 'Cum Se Evaluează o Companie',
        description: 'Revenue Multiple, EBITDA Multiple, Asset-Based, DCF. Pre-money vs. post-money. Diluarea.',
        video_url: '',
        duration_min: 0,
        order_index: 2,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-9-3',
        module_id: 'st-m-9',
        title: 'Ce Caută Investitorii',
        description: 'Echipa, tracțiunea, piața, modelul, sistemul, finanțele curate. Dacă ai executat modulele 1–8, ești deja investment-ready în principiu.',
        video_url: '',
        duration_min: 0,
        order_index: 3,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-9-4',
        module_id: 'st-m-9',
        title: 'Procesul Pas cu Pas: De la Căutare la Closing',
        description: 'Materiale, investitorul potrivit, pitch, due diligence, term sheet, closing.',
        video_url: '',
        duration_min: 0,
        order_index: 4,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-9-5',
        module_id: 'st-m-9',
        title: 'Greșelile Care Distrug Deal-urile',
        description: 'Cauți prea devreme, dai prea mult equity, iei orice bani, nu protejezi IP-ul, confunzi valoarea cu ego-ul.',
        video_url: '',
        duration_min: 0,
        order_index: 5,
        is_published: false,
        type: 'video',
      },
      {
        id: 'st-l-9-ex-1',
        module_id: 'st-m-9',
        title: 'Livrabilul modulului · Cum Funcționează Investițiile',
        description: 'Înțelegi mecanismele de investiție, știi ce face o afacere investabilă, poți calcula o evaluare simplă și identifici ce tip de capital ți se potrivește.',
        video_url: '',
        duration_min: 0,
        order_index: 6,
        is_published: true,
        type: 'exercise',
        exercise_id: 'st-e-9-1',
      },
    ],
    exercises: [
      {
        id: 'st-e-9-1',
        module_id: 'st-m-9',
        title: 'Livrabilul modulului · Cum Funcționează Investițiile',
        description: 'Înțelegi mecanismele de investiție, știi ce face o afacere investabilă, poți calcula o evaluare simplă și identifici ce tip de capital ți se potrivește.',
        order_index: 1,
      },
    ],
  },
];

/** Evenimentele live ale cursului Start — apeluri de grup + workshopuri. */
export const START_LIVE_EVENTS: LiveEvent[] = [];
