/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminProgressRouteImport } from './routes/admin.progress'
import { Route as AdminLessonsRouteImport } from './routes/admin.lessons'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AdminStudentUserIdRouteImport } from './routes/admin.student.$userId'
import { Route as AppModuleIdRouteImport } from './routes/_app.module.$id'
import { Route as AppLessonIdRouteImport } from './routes/_app.lesson.$id'
import { Route as AppDocumentsDocIdFillRouteImport } from './routes/_app.documents.$docId.fill'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgressRoute = AdminProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLessonsRoute = AdminLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AdminStudentUserIdRoute = AdminStudentUserIdRouteImport.update({
  id: '/student/$userId',
  path: '/student/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AppModuleIdRoute = AppModuleIdRouteImport.update({
  id: '/module/$id',
  path: '/module/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppLessonIdRoute = AppLessonIdRouteImport.update({
  id: '/lesson/$id',
  path: '/lesson/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsDocIdFillRoute = AppDocumentsDocIdFillRouteImport.update({
  id: '/$docId/fill',
  path: '/$docId/fill',
  getParentRoute: () => AppDocumentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/quiz': typeof QuizRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/welcome': typeof WelcomeRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRouteWithChildren
  '/admin/activity': typeof AdminActivityRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/progress': typeof AdminProgressRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/lesson/$id': typeof AppLessonIdRoute
  '/module/$id': typeof AppModuleIdRoute
  '/admin/student/$userId': typeof AdminStudentUserIdRoute
  '/documents/$docId/fill': typeof AppDocumentsDocIdFillRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/quiz': typeof QuizRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/welcome': typeof WelcomeRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRouteWithChildren
  '/admin/activity': typeof AdminActivityRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/progress': typeof AdminProgressRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/lesson/$id': typeof AppLessonIdRoute
  '/module/$id': typeof AppModuleIdRoute
  '/admin/student/$userId': typeof AdminStudentUserIdRoute
  '/documents/$docId/fill': typeof AppDocumentsDocIdFillRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/quiz': typeof QuizRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/welcome': typeof WelcomeRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documents': typeof AppDocumentsRouteWithChildren
  '/admin/activity': typeof AdminActivityRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/progress': typeof AdminProgressRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/lesson/$id': typeof AppLessonIdRoute
  '/_app/module/$id': typeof AppModuleIdRoute
  '/admin/student/$userId': typeof AdminStudentUserIdRoute
  '/_app/documents/$docId/fill': typeof AppDocumentsDocIdFillRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/quiz'
    | '/register'
    | '/reset-password'
    | '/welcome'
    | '/dashboard'
    | '/documents'
    | '/admin/activity'
    | '/admin/lessons'
    | '/admin/progress'
    | '/admin/users'
    | '/admin/'
    | '/lesson/$id'
    | '/module/$id'
    | '/admin/student/$userId'
    | '/documents/$docId/fill'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/quiz'
    | '/register'
    | '/reset-password'
    | '/welcome'
    | '/dashboard'
    | '/documents'
    | '/admin/activity'
    | '/admin/lessons'
    | '/admin/progress'
    | '/admin/users'
    | '/admin'
    | '/lesson/$id'
    | '/module/$id'
    | '/admin/student/$userId'
    | '/documents/$docId/fill'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/quiz'
    | '/register'
    | '/reset-password'
    | '/welcome'
    | '/_app/dashboard'
    | '/_app/documents'
    | '/admin/activity'
    | '/admin/lessons'
    | '/admin/progress'
    | '/admin/users'
    | '/admin/'
    | '/_app/lesson/$id'
    | '/_app/module/$id'
    | '/admin/student/$userId'
    | '/_app/documents/$docId/fill'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  QuizRoute: typeof QuizRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/progress': {
      id: '/admin/progress'
      path: '/progress'
      fullPath: '/admin/progress'
      preLoaderRoute: typeof AdminProgressRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lessons': {
      id: '/admin/lessons'
      path: '/lessons'
      fullPath: '/admin/lessons'
      preLoaderRoute: typeof AdminLessonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/student/$userId': {
      id: '/admin/student/$userId'
      path: '/student/$userId'
      fullPath: '/admin/student/$userId'
      preLoaderRoute: typeof AdminStudentUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/module/$id': {
      id: '/_app/module/$id'
      path: '/module/$id'
      fullPath: '/module/$id'
      preLoaderRoute: typeof AppModuleIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lesson/$id': {
      id: '/_app/lesson/$id'
      path: '/lesson/$id'
      fullPath: '/lesson/$id'
      preLoaderRoute: typeof AppLessonIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents/$docId/fill': {
      id: '/_app/documents/$docId/fill'
      path: '/$docId/fill'
      fullPath: '/documents/$docId/fill'
      preLoaderRoute: typeof AppDocumentsDocIdFillRouteImport
      parentRoute: typeof AppDocumentsRoute
    }
  }
}

interface AppDocumentsRouteChildren {
  AppDocumentsDocIdFillRoute: typeof AppDocumentsDocIdFillRoute
}

const AppDocumentsRouteChildren: AppDocumentsRouteChildren = {
  AppDocumentsDocIdFillRoute: AppDocumentsDocIdFillRoute,
}

const AppDocumentsRouteWithChildren = AppDocumentsRoute._addFileChildren(
  AppDocumentsRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRouteWithChildren
  AppLessonIdRoute: typeof AppLessonIdRoute
  AppModuleIdRoute: typeof AppModuleIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRouteWithChildren,
  AppLessonIdRoute: AppLessonIdRoute,
  AppModuleIdRoute: AppModuleIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminLessonsRoute: typeof AdminLessonsRoute
  AdminProgressRoute: typeof AdminProgressRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminStudentUserIdRoute: typeof AdminStudentUserIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminLessonsRoute: AdminLessonsRoute,
  AdminProgressRoute: AdminProgressRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminStudentUserIdRoute: AdminStudentUserIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  QuizRoute: QuizRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
